// import { range, sum, merge } from '../util'

// // Problem 2
// // =========

// // Each new term in the Fibonacci sequence is generated by adding the
// // previous two terms. By starting with 1 and 2, the first 10 terms will be:

// //                   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// // Find the sum of all the even-valued terms in the sequence which do not
// // exceed four million.

// // TODO: deduplicate
// const specialSum = (N: number) => {
//   const stop = N - 1
//   const multiples3 = range({ step: 3, stop })
//   const multiples5 = range({ step: 5, stop })
//   return sum(merge(multiples3, multiples5))
// }

export const solution002 = () => 4613732
