import { Sequence } from 'lib/Sequence'

// Pentagon numbers
// ================
// Pentagonal numbers are generated by the formula, P[n]=n(3n-1)/2. The first
// ten pentagonal numbers are:
//
//                1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
//
// It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
// difference, 70 - 22 = 48, is not pentagonal.
//
// Find the pair of pentagonal numbers, P[j] and P[k], for which their sum
// and difference is pentagonal and D = |P[k] - P[j]| is minimised; what is
// the value of D?

const P = new Sequence((n: number) => (n * (3 * n - 1)) / 2)

expect(P.valuesUpTo(60)).toEqual([1, 5, 12, 22, 35, 51])
expect(P.valuesUpTo(145)).toEqual([1, 5, 12, 22, 35, 51, 70, 92, 117, 145])

expect(P.includes(P.value(4) + P.value(7))).toBe(true)
expect(P.includes(P.value(7) - P.value(4))).toBe(false)

export const solution044 = () => {
  let n = 2
  let solution: { pk: number; pj: number } | undefined
  while (solution === undefined) {
    const pk = P.value(n++)
    const valuesBelow = P.valuesUpTo(pk - 1)
    for (const pj of valuesBelow)
      if (P.includes(pk - pj) && P.includes(pk + pj)) solution = { pk, pj }
  }
  const { pk, pj } = solution
  return pk - pj
}
